// Shrinks photos in public/images and regenerates their blur placeholders.
// Run after adding new photos:  node scripts/optimize-images.mjs
import fs from "node:fs"
import path from "node:path"
import sharp from "sharp"

const DIR = "public/images"
const MAX = 1800
const OUT = "lib/image-blur.ts"

const files = fs.readdirSync(DIR).filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
const blur = {}
let before = 0
let after = 0

for (const f of files) {
  const file = path.join(DIR, f)
  const input = fs.readFileSync(file)
  before += input.length
  const meta = await sharp(input).metadata()
  if (meta.width > MAX || meta.height > MAX || input.length > 300_000) {
    const out = await sharp(input)
      .rotate()
      .resize({ width: MAX, height: MAX, fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: 74, mozjpeg: true, progressive: true })
      .toBuffer()
    if (out.length < input.length) fs.writeFileSync(file, out)
  }
  after += fs.statSync(file).size
  const tiny = await sharp(file).resize(16, 16, { fit: "inside" }).jpeg({ quality: 50 }).toBuffer()
  blur[`/images/${f}`] = `data:image/jpeg;base64,${tiny.toString("base64")}`
}

fs.writeFileSync(
  OUT,
  `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\nexport const IMAGE_BLUR: Record<string, string> = ${JSON.stringify(blur, null, 2)}\n`,
)
console.log(`${files.length} images: ${(before / 1048576).toFixed(1)}MB -> ${(after / 1048576).toFixed(1)}MB`)
